### ISSUE TITLE
Chromeがクラッシュするらしい

### ISSUE THREAD

**Issue by tmyt** [tmyt/VDMHelper#9]
Refer: http://stackoverflow.com/a/33206122

**Comment by Grabacr07** [comment]
ちょっと 3 行でおねがい

**Comment by tmyt** [comment]
このリポジトリのリファラ眺めてたら見つけたStackOverflowにこう書いてた

> The second implementation can be found here: https://github.com/tmyt/VDMHelper This one can move a window from another process to another desktop. BUT it is buggy right now. For exemple when i try to move some window like google chrome it crash.
> Refer: http://stackoverflow.com/a/33206122

**Comment by Grabacr07** [comment]
Chrome つかってるけど死んだことないなあ

**Comment by tmyt** [comment]
あそこに、どういう環境なんだい？って書きこんでみる遊びとかどうだろう

**Comment by tmyt** [comment]
Concurrentバグがあるかもしれない。要調査

Grabacr07/SylphyHorn#13

**Comment by tmyt** [comment]
同一プロセスに所属するウィンドウを同時に複数移動させるとまずいのか？

**Comment by tmyt** [comment]
なおりました。
